# Site settings
title: Adventures in Code 
email: ruthan@ceilingpunch.es 
description: "powered by tea"
baseurl: ""  ## FIXME 
url: "http://ceilingpunch.es"

# Build settings
markdown: kramdown
permalink: pretty
name: Adventures in Code # this is the blog title
pygments: true
highlighter: pygments
