# Site settings
title: Your awesome title
email: your-email@domain.com
description: "powered by tea"
baseurl: ""  ## FIXME 
url: "http://ceilingpunch.es"

# Build settings
markdown: kramdown
permalink: pretty
name: Adventures in Code School # this is the blog title
pygments: true
highlighter: pygments
