# Site settings
title: Adventures in Code 
description: "powered by tea"
baseurl: ""  ## FIXME 

# Build settings
markdown: kramdown
permalink: pretty
name: Adventures in Code # this is the blog title
highlighter: rouge
