post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/
